language: python
python: "3.7.2"
dist: 'xenial'

install:
  - pip install -r requirements.txt
  - curl -L https://releases.hashicorp.com/packer/1.3.4/packer_1.3.4_linux_amd64.zip -o /tmp/packer.zip
  - sudo unzip -o -d /usr/local/bin /tmp/packer.zip
  - sudo chmod +x /usr/local/bin/packer

before_script:
 - python ./scripts/remove_packer_images.py
 - /usr/local/bin/packer validate ./packer/digital_ocean.json

script:
  - /usr/local/bin/packer build ./packer/digital_ocean.json