# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  delete-packer:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.4

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./scripts/packer_removal/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r ./scripts/packer_removal/requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "./scripts/packer_removal/requirements.txt" }}

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run packer removal
          command: |
            . venv/bin/activate
            python ./scripts/packer_removal/remove_packer_images.py
  new-image:
    environment:
      PACKER_VERSION: '1.4.3'
    machine: true
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            curl -L https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip -o /tmp/packer.zip
            sudo unzip -o -d /usr/local/bin /tmp/packer.zip
            sudo chmod +x /usr/local/bin/packer

      - run:
          name: validate packer
          command: /usr/local/bin/packer validate ./packer/digital_ocean.json

      - run:
          name: build packer
          command: /usr/local/bin/packer build ./packer/digital_ocean.json

workflows:
  version: 2
  delete-packer-then-new-image:
    jobs:
      - delete-packer
      - new-image:
          requires:
            - delete-packer